try nfs method

diff --git a/roles/media_share/tasks/main.yml b/roles/media_share/tasks/main.yml
--- a/roles/media_share/tasks/main.yml
+++ b/roles/media_share/tasks/main.yml
@@ -9,23 +9,25 @@
     msg: "filtered_idracs value: {{ filtered_idracs }}"
   when: debug is defined and debug | bool
 
-- name:  Open port {{ media_share_webserver_port }} on the firewall
-  firewalld: 
-    port: "{{ media_share_webserver_port }}/tcp"
-    permanent: no
-    immediate: yes
-    state: enabled
-  become: true
-  when: (media_share_idrac | bool and filtered_idracs | length > 0) or media_share_webserver | bool
+# - name:  Open port {{ media_share_webserver_port }} on the firewall
+#   firewalld: 
+#     port: "{{ media_share_webserver_port }}/tcp"
+#     permanent: no
+#     immediate: yes
+#     state: enabled
+#   become: true
+#   when: (media_share_idrac | bool and filtered_idracs | length > 0) or media_share_webserver | bool
 
-- name: Create the temporary webserver | runs in background via tmux
-  shell: |
-    if ! tmux has-session -t temp-webserver 2>/dev/null; then
-      tmux new-session -d -s temp-webserver python3 -m http.server
-    fi
-  args:
-    chdir: "{{ common_openshift_cluster_install_dir }}"
-  failed_when: false
+# - name: Create the temporary webserver | runs in background via tmux
+#   shell: |
+#     if ! tmux has-session -t temp-webserver 2>/dev/null; then
+#       tmux new-session -d -s temp-webserver python3 -m http.server
+#     fi
+#   args:
+#     chdir: "{{ common_openshift_cluster_install_dir }}"
+#   failed_when: false
+#   when: (media_share_idrac | bool and filtered_idracs | length > 0) or media_share_webserver | bool
+- ansible.builtin.include_tasks: nfs_setup.yml
   when: (media_share_idrac | bool and filtered_idracs | length > 0) or media_share_webserver | bool
 
 - ansible.builtin.include_tasks: idrac.yml
@@ -34,6 +36,6 @@
     loop_var: media_share_idracs
   when: media_share_idrac | bool and  filtered_idracs | length > 0
 
-- ansible.builtin.include_tasks: stop_temp_web_server.yml
-  when: media_share_stop_webserver | bool
+# - ansible.builtin.include_tasks: stop_temp_web_server.yml
+#   when: media_share_stop_webserver | bool
 
